### ISSUE TITLE
Add ability to auto-skip prompting for value of parameter data when not found automatically

### ISSUE THREAD

**Issue by atanisoft** [30350n/inventree_part_import#55]
In some cases users will have the KiCad integration enabled on the Inventree side and have virtual parameters defined on parts for such usages. If we do not declare these as part of categories.yaml then we get a warning for mismatch, if we do define it in categories.yaml then we are subjected to prompting (default behavior) when the value can not be determined automatically.

It would be ideal if we could declare the category as:

```
    Antennas:
        _parameters:
            - Frequency
            - Gain (dBi)
            - Impedance
            - Rated Power
        _optionalParameters:
            - Symbol Type          
```

Or similar notation that would allow defining of a parameter on the parts to collect if found but skipped when not found. The parameter should still be created on the relevant parts regardless of a value being assigned during import. Optionally the tool could dump a list of parts that have optional parameters that could not be resolved (similar to the current incomplete import but calling it out for optional parameters).
