### ISSUE TITLE
Problem Manually Entering Category

### ISSUE THREAD

**Issue by bear-fighter** [30350n/inventree_part_import#68]
When importing a part and being prompted to select a category, I trying entering manually but get the following error(s).  I've tried every combination of path to the "Electronics/Connectors/Power" category and nothing seems to provide a match.  Is there a special syntax for manually entering the path?

```
gabe@zeus-server:~$ inventree-part-import 732-10898-1-ND
(only 1 of 5 available supplier modules are configured)
successfully setup categories!

searching for 732-10898-1-ND ...
importing DigiKey part 732-10898-2-ND ...
error: failed to match category for 'Connectors, Interconnects / Terminals / Screw Connectors'

reimporting failed/incomplete parts in interactive mode ...

searching for 732-10898-1-ND ...

failed to match category for 'Connectors, Interconnects / Terminals / Screw Connectors', select category:
  Electronics / Connectors / Barrel Connectors
  Electronics / Connectors / Circular Connectors
  Electronics / Connectors / Audio Connectors
  Electronics / Connectors / FPC
  Electronics / Connectors / Header
> Enter Manually ...
  Skip ...
category name: Power
warning: category 'Power' does not exist

select category:
  Electronics / Connectors / Barrel Connectors
  Electronics / Connectors / Circular Connectors
  Electronics / Connectors / Audio Connectors
  Electronics / Connectors / FPC
  Electronics / Connectors / Header
> Enter Manually ...
  Skip ...
category name: Electronics/Connectors/Power
warning: category 'Electronics/Connectors/Power' does not exist

select category:
> Electronics / Connectors / Barrel Connectors
  Electronics / Connectors / Circular Connectors
  Electronics / Connectors / Audio Connectors
  Electronics / Connectors / FPC
  Electronics / Connectors / Header
  Enter Manually ...
  Skip ...
```

Here is a copy of my categories.yaml file:

```
Assemblies:
    Printed-Circuit Board Assembly:
        _description: ''
    Product:
        _description: ''
    _description: ''
Circuit Protections:
    Fuses:
        _description: ''
    PTC:
        _description: ''
    TVS:
        _description: ''
    _description: ''
Connectors:
    _description: ''
Electronics:
    Cables and Wires:
    Connectors:
        Audio Connectors:
            _parameters:
                - Connector Type
                - Mounting Type
                - Rated Current
                - Rated Voltage
        Barrel Connectors:
            _parameters:
                - Connector Type
                - Mounting Type
                - Rated Current
                - Rated Voltage
        Battery:
            _description: ''
        Board-to-Board:
            _description: ''
        Circular Connectors:
            _parameters:
                - Connector Type
                - Mounting Type
                - Number of Contacts
                - Rated Current
                - Rated Voltage
        Coaxial:
            _description: ''
        Connector Housings:
            _parameters:
                - Connector Type
                - Number of Contacts
                - Number of Rows
        FPC:
            _description: ''
        Header:
            _description: ''
        Interface:
            _description: Connectors for Digital Interfaces
            _parameters:
                - Mounting Type
                - Number of Contacts
        Jumpers:
            _description: Jumpers, Shunts
            _parameters:
                - Number of Contacts
                - Pitch
                - Rated Current
                - Rated Voltage
        Power:
            _description: Power Connectors
            _parameters:
                - Number of Contacts
        Rectangular:
            _parameters:
                - Connector Type
                - Mounting Type
                - Number of Contacts
                - Number of Rows
                - Pitch
                - Rated Current
                - Rated Voltage
    Crystals, Oscillators:
        Crystals:
            _parameters:
                - ESR
        Oscillators:
        _parameters:
            - Frequency
            - Mounting Type
            - Package / Case
            - Package Type
            - Size
    Diodes:
        LED:
            _description: ''
        LEDs:
            _parameters:
                - Color
        Schottky:
            _description: Schottky Diodes
            _parameters:
                - Rated Current
                - Reverse Breakdown Voltage
        Standard:
            _description: Standard Rectifier Diodes, Small Signal Diodes
            _parameters:
                - Rated Current
                - Reverse Breakdown Voltage
        TVS:
            _description: Transient-Voltage-Suppression Diodes
            _parameters:
                - Current - Peak Pulse (10/1000µs)
                - Power - Peak Pulse
                - Rated Current
                - Voltage - Breakdown (Min)
                - Voltage - Clamping (Max) @ Ipp
                - Voltage - Reverse Standoff (Typ)
        Zener:
            _description: Zener Diodes
            _parameters:
                - Rated Power
                - Reverse Breakdown Voltage
        _parameters:
            - Forward Voltage
            - Mounting Type
            - Package / Case
            - Package Type
    Electromechanical:
        Motors:
        Potentiometers:
            _parameters:
                - Mounting Type
                - Rated Power
                - Resistance
                - Tolerance
        Relays:
            _parameters:
                - Mounting Type
                - Rated Current
                - Rated Voltage
        Switches:
            _parameters:
                - Mounting Type
                - Rated Current
                - Rated Voltage
        _description: Electromechanical Components
    Integrated Circuits:
        Amplifiers:
            Instrumentation Amplifiers:
            Operational Amplifiers:
            _description: Amplifier ICs
            _parameters:
                - Supply Voltage
        Audio:
            _description: Audio ICs
        Data Acquisition:
            ADCs:
                _description: Analog to Digital Converters
            DACs:
                _description: Digital to Analog Converters
            _description: Data Acquisition ICs
        Interface:
            Analog Switches:
            Audio Codecs:
            IO Expanders:
            Transceivers:
            _description: Interface ICs
            _parameters:
                - Supply Voltage
        Logic:
            Counters:
            Flip Flops:
            Logic Gates:
            PLLs:
                _description: Phase-Locked Loops
            Shift Registers:
            _description: Logic ICs
            _parameters:
                - Supply Voltage
        Memory:
            _description: Memory ICs
        Microcontrollers:
            _parameters:
                - Frequency
                - Supply Voltage
        Motor Drivers:
            _parameters:
                - Output Current
                - Rated Voltage
                - Supply Voltage
        Optoisolators:
            _parameters:
                - Forward Voltage
                - Output Current
                - Rated Current
                - Supply Voltage
        Power:
            DC-DC Converters:
                _parameters:
                    - Input Voltage
                    - Output Current
                    - Output Voltage
                    - Rated Power
            Low Dropout Regulators:
                _parameters:
                    - Input Voltage
                    - Output Current
                    - Output Polarity
                    - Output Type
                    - Output Voltage
            Switching Regulators:
                _parameters:
                    - Frequency
                    - Input Voltage
                    - Output Current
                    - Output Voltage
                    - Type
            Voltage References:
                _parameters:
                    - Input Voltage
                    - Output Current
                    - Output Voltage
                    - Tolerance
            _description: Power ICs
        _parameters:
            - Mounting Type
            - Package / Case
            - Package Type
    Passives:
        Capacitors:
            _parameters:
                - Capacitance
                - Rated Voltage
                - Tolerance
        Ferrite Beads:
            _parameters:
                - Impedance
                - Rated Current
                - Resistance
        Inductors:
            _parameters:
                - Inductance
                - Rated Current
                - Size
                - Tolerance
        PTC Resettable Fuses:
            _parameters:
                - Rated Voltage
        Resistors:
            _parameters:
                - Rated Power
                - Resistance
                - Tolerance
        _description: Passive Components
        _parameters:
            - Mounting Type
            - Package / Case
            - Package Type
    Transistors:
        Bipolar:
            NPN:
                _description: Bipolar NPN Transistors
            PNP:
                _description: Bipolar PNP Transistors
            _description: Bipolar Transistors
            _parameters:
                - Gain (hFE)
                - Rated Current
                - Rated Power
                - Rated Voltage
        JFETs:
            N-Channel JFETs:
            P-Channel JFETs:
            _description: Junction-Gate Field-Effect Transistors
            _parameters:
                - Rated Power
                - Rated Voltage
        MOSFETs:
            N-Channel MOSFETs:
            P-Channel MOSFETs:
            _description: Metal-Oxide-Semiconductor Field-Effect Transistors
            _parameters:
                - Rated Current
                - Rated Voltage
        _parameters:
            - Mounting Type
            - Package / Case
            - Package Type
    _description: Electronic Components
Fuses:
    _description: ''
Mechanical:
    Hardware:
        Nuts:
        Screws:
        Standoffs:
        Washers:
Mechanicals:
    Nuts:
        _description: ''
    Screws:
        _description: ''
    Standoff:
        _description: ''
    Switch:
        _description: ''
    _description: ''
Miscellaneous:
    Batteries:
        _description: ''
    _description: ''
Modules:
    _description: ''
PCBs:
    _description: Printed Circuit Boards
PTC:
    _description: ''
Power Management:
    Boost:
        _description: ''
    Buck:
        _description: ''
    LDO:
        _description: ''
    PMIC:
        _description: ''
    _description: ''
Printed-Circuit Boards:
    _description: ''
RF:
    Antenna:
        _description: ''
    Chipset:
        _description: ''
    Filter:
        _description: ''
    Shield:
        _description: ''
    _description: ''

```
